// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		MsgProvider: typeof import('./src/components/msg-provider.vue')['default'];
		NAvatar: typeof import('naive-ui')['NAvatar'];
		NBreadcrumb: typeof import('naive-ui')['NBreadcrumb'];
		NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem'];
		NButton: typeof import('naive-ui')['NButton'];
		NCard: typeof import('naive-ui')['NCard'];
		NCheckbox: typeof import('naive-ui')['NCheckbox'];
		NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
		NDataTable: typeof import('naive-ui')['NDataTable'];
		NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
		NDivider: typeof import('naive-ui')['NDivider'];
		NDrawer: typeof import('naive-ui')['NDrawer'];
		NDrawerContent: typeof import('naive-ui')['NDrawerContent'];
		NDropdown: typeof import('naive-ui')['NDropdown'];
		NForm: typeof import('naive-ui')['NForm'];
		NFormItem: typeof import('naive-ui')['NFormItem'];
		NH3: typeof import('naive-ui')['NH3'];
		NH6: typeof import('naive-ui')['NH6'];
		NIcon: typeof import('naive-ui')['NIcon'];
		NInput: typeof import('naive-ui')['NInput'];
		NLayout: typeof import('naive-ui')['NLayout'];
		NLayoutContent: typeof import('naive-ui')['NLayoutContent'];
		NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
		NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
		NNotificationProvider: typeof import('naive-ui')['NNotificationProvider'];
		NPopover: typeof import('naive-ui')['NPopover'];
		NResult: typeof import('naive-ui')['NResult'];
		NSpace: typeof import('naive-ui')['NSpace'];
		NSwitch: typeof import('naive-ui')['NSwitch'];
		NTooltip: typeof import('naive-ui')['NTooltip'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
	}
}
