name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use Node.js 16
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'

      - name: use pnpm 6.32.2
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.2

      - name: Build
        run: |
          pnpm install
          pnpm run build:staging

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
